// <auto-generated />
namespace Better.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changed_user_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_user_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201912081116572_changed_user_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
