// <auto-generated />
namespace Better.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_posts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_posts));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121012404_added_posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
