// <auto-generated />
namespace Better.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_creationdate_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_creationdate_post));
        
        string IMigrationMetadata.Id
        {
            get { return "201912190921133_added_creationdate_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
