// <auto-generated />
namespace Better.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addfriendslist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfriendslist));
        
        string IMigrationMetadata.Id
        {
            get { return "202005300435438_add-friends-list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
