// <auto-generated />
namespace Better.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_post_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_post_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202005291510566_add_post_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
